export default {
	HAD: 'Home/Away/Draw',
	FHAD:'FHAD',
	HHAD:'Handicap Had',
	HDC:'Handicap',
	HFT:'HaFu',
	TQL:'To Qualify',
	CRS:'Correct Score',
	FCS:'FCS',
	TTG:'Total Goals',
	OOE:'Odd/Even',
	HILO:'HILO',
	FHL:'FHL',
	CHLO:'Corner HiLo',
	PS:'Player specials',
	GPW:'Group Winner',
	GPF:'Group Forecast',
	TPS:'Top Scorer',
	FGS:'First Goal Scorer',
	FTS:'FTS',
	CP:'Champion',
	DHCP:'Double Hafu Score',
	'6FH':'6 HaFu',
}